# https://taskfile.dev

version: '3'

tasks:
    run:
        desc: "run the url shortener"
        cmds:
            - task migrate
            - CONFIG_PATH=config/local.yaml go run ./cmd/random-history-facts
    migrate:
        desc: "init all required tables"
        cmds:
            - go run ./cmd/migrator --config=config/migration.yaml
    migrate-down:
        desc: "drop all tables"
        cmds:
            - go run ./cmd/migrator --config=config/migration.yaml --operation=down